services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Exposing port 3000
    volumes:
      - ./backend:/usr/src/app
      - ./frontend:/usr/src/app/public
    restart: unless-stopped
