services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Exposing port 3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app/public
    restart: unless-stopped
    command: npx nodemon --watch . --ext js,json app.js
  # Frontend service
  # live code for FE update at localhost:8080
  frontend:
    container_name: frontend
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: npx live-server --port=8080 --open=/index.html --watch=.